#
# This file will be copied into:
#
#  /opt/spark/conf/spark-defaults.conf
#
#------------------------------------------

# Catalog configuration
spark.sql.catalogImplementation=hive
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.sources.default=delta

# Delta schema options
spark.databricks.delta.schema.autoMerge.enabled=true

# Warehouse location
spark.sql.warehouse.dir=/workspaces/spark-sandbox/warehouse