#
# This file will be copied into:
#
#  /opt/spark/conf/spark-defaults.conf
#
#------------------------------------------

# Catalog configuration
spark.sql.catalogImplementation=hive
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.sources.default=delta

# Delta schema options
spark.databricks.delta.schema.autoMerge.enabled=true

# Warehouse location
spark.sql.warehouse.dir=/workspaces/spark-sandbox/warehouse

# OpenLineage configuration
spark.jars.packages=io.openlineage:openlineage-spark_2.12:1.26.0
spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.transport.type=file
spark.openlineage.transport.location=/workspaces/spark-sandbox/projects/spark-scala/.temp/openlineage/lineage-from-spark-default.json