version: 2

seeds:
  - name: productcategory
    config:
      schema: dbt_adventureworks_seed
      column_types:
        productcategoryid: integer
        name: string
        modifieddate: timestamp
