[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spark-dbt"
version = "0.1.0"
description = 'dbt project for Fabric Spark and local runs'
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  { name = "Raki Rahman", email = "mdrakiburrahman@gmail.com" },
]

[tool.hatch.envs.default]
type = "virtual"
path = ".venv"
skip-install = true
dependencies = [
  "dbt-fabricspark @ git+https://github.com/microsoft/dbt-fabricspark.git@main",
  "dbterd",
  "dbt-artifacts-parser",
]

[tool.hatch.envs.default.env-vars]
UV_PRERELEASE = "allow"

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Documentation = "https://github.com/mdrakiburrahman/spark-sandbox#readme"
Issues = "https://github.com/mdrakiburrahman/spark-sandbox/issues"
Source = "https://github.com/mdrakiburrahman/spark-sandbox"
