jaffle_shop:
  target: local-local
  outputs:
    # Local dbt client + Local spark server (default for development)
    local-local:
      authentication: cli
      method: livy
      livy_mode: local
      session_id_file: /workspaces/spark-sandbox/projects/spark-dbt/livy-session-id.txt
      connect_retries: 25
      connect_timeout: 10
      lakehouse: dbt_jaffle_shop_dwh
      schema: dbt_jaffle_shop_dwh
      threads: 12
      type: fabricspark
      retry_all: true
      spark_config:
        name: dbt-jaffle-shop

    # Local dbt client + Fabric spark server
    local-fabric:
      authentication: cli
      method: livy
      livy_mode: fabric
      session_id_file: /workspaces/spark-sandbox/projects/spark-dbt/livy-session-id.txt
      connect_retries: 25
      connect_timeout: 10
      endpoint: https://api.fabric.microsoft.com/v1
      workspaceid: 3ea60ae5-e979-4d31-a317-66491ab497fb
      lakehouseid: a1340f32-34c8-494a-9628-8c5d5f03f284
      lakehouse: dbt_jaffle_shop_dwh
      schema: dbt_jaffle_shop_dwh
      threads: 12
      type: fabricspark
      retry_all: true
      spark_config:
        name: dbt-jaffle-shop

    # Fabric dbt client + Fabric spark server
    fabric-fabric:
      authentication: fabric_notebook
      method: livy
      livy_mode: fabric
      session_id_file: /tmp/dbt-fabric-bundle/projects/dbt-jaffle-shop/livy-session-id.txt
      connect_retries: 1
      connect_timeout: 60
      endpoint: https://api.fabric.microsoft.com/v1
      workspaceid: 3ea60ae5-e979-4d31-a317-66491ab497fb
      lakehouseid: a1340f32-34c8-494a-9628-8c5d5f03f284
      lakehouse: dbt_jaffle_shop_dwh
      schema: dbt_jaffle_shop_dwh
      threads: 12
      type: fabricspark
      retry_all: true
      spark_config:
        name: dbt-jaffle-shop
