name: Deploy Fabric

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-fabric-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_GH_ACTION: "1"
  IMDS_ROUTER_PORT: "8080"
  IMDS_METADATA_ENDPOINT: "http://localhost:8080/metadata/instance?api-version=2025-04-07"
  IDENTITY_ENDPOINT: "http://localhost:8080/metadata/identity/oauth2/token"
  IDENTITY_HEADER: "local-dev-secret"
  UAMI_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  UAMI_SUBSCRIPTION: "00000000-0000-0000-0000-000000000000"

jobs:
  deploy:
    runs-on: [self-hosted, spark-sandbox-azure]
    container:
      image: rakirahman.azurecr.io/devcontainer/spark:2d6281b13738c8576a232df9a708f5c083820105d8d3f6d4696c28aa99bb091e
      options: >-
        --cap-add=SYS_ADMIN
        --device=/dev/fuse
        --security-opt=apparmor:unconfined
        --add-host=host.docker.internal:host-gateway

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/auth
        with:
          imds-relay-url: ${{ secrets.IMDS_RELAY_URL }}
          imds-relay-sender-key: ${{ secrets.IMDS_RELAY_SENDER_KEY }}

      - name: "🚀 Deploy"
        env:
          MARQUITO_WEBSITE_STORAGE_CONN_STRING: ${{ secrets.MARQUITO_WEBSITE_STORAGE_CONN_STRING }}
        run: npx nx run-many -t deploy --verbose --output-style=stream
